spring:
  application:
    name: "order-service"
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        service: order-service
      config:
        namespace: dev
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      enabled: true
      web-context-unify: false
  config:
    import:
      - classpath:application-feign.yaml
      - nacos:service-order.properties
      - nacos:data-order.properties
    name: service-order

server:
  port: 8000
